deployment:
	west build -b deployment_module app/backplane/deployment_module -p auto -DDEBUG=y

deployment-sim:
	west build -b native_sim app/backplane/deployment_module -p auto -DDEBUG=y

deployment-flight:
	west build -b deployment_module app/backplane/deployment_module -p auto
