sensor:
	west build -b sensor_module app/backplane/sensor_module -p auto -DDEBUG=y

sensor-sim:
	west build -b native_sim app/backplane/sensor_module -p auto -DDEBUG=y

sensor-flight:
	west build -b sensor_module app/backplane/sensor_module -p auto
