# Copyright (c) 2024 RIT Launch Initiative
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: zscilib
      url-base: https://github.com/zephyrproject-rtos/zscilib

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.1.0
      import:
        name-allowlist:
          - cmsis
          - hal_st
          - hal_stm32
          - hal_nxp
          - littlefs
          - loramac-node
          - lz4
          - segger
          - percepio
          - zscilib
      clone-depth: 1

