CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_I2C_STM32_BUS_RECOVERY=y
CONFIG_SPI=y
CONFIG_SPI_SLAVE=y
CONFIG_SPI_STM32_INTERRUPT=y
CONFIG_SPI_STM32_DMA=y
CONFIG_DMA=y
#CONFIG_SYS_CLOCK_TICKS_PER_SEC=10000
CONFIG_LOG_PRINTK=y
CONFIG_SHELL=y
CONFIG_I2C_SHELL=y
CONFIG_I2C_STM32_BUS_RECOVERY=y
CONFIG_GPIO_SHELL=n
CONFIG_SHELL_BACKEND_SERIAL=y
# CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_GLIBCXX_LIBCPP=y

CONFIG_REBOOT=y



CONFIG_DEVMEM_SHELL=n
CONFIG_DEVICE_SHELL=n
CONFIG_DATE_SHELL=n
CONFIG_SHELL_MINIMAL=y
CONFIG_SHELL_VT100_COMMANDS=n

CONFIG_LIS2DH=y
CONFIG_LIS2DH_ODR_6=y
CONFIG_LIS2DH_ACCEL_RANGE_8G=y
#cm
