#ifndef REEFER_INCLUDE_CONFIG_H
#define REEFER_INCLUDE_CONFIG_H

#define SAMPLE_RATE_HZ 1000
#define TEST_DURATION 10
#define MAX_TESTS 30

#define STORAGE_THREAD_PRIORITY   1
#define ADC_READ_PRIORITY  -1
#define THREAD_START_DELAY 100

#define ADC_BUFFER_SIZE  (SAMPLE_RATE_HZ* TEST_DURATION_SEC)
#define FLASH_BLOCK_SIZE (ADC_BUFFER_SIZE* sizeof(uint32_t))

#endif // REEFER_INCLUDE_CONFIG_H