#ifndef REEFER_INCLUDE_CONFIG_H
#define REEFER_INCLUDE_CONFIG_H

#define SAMPLE_RATE_HZ 1000
#define TEST_DURATION 10
#define MAX_TESTS 30

#define STORAGE_THREAD_PRIORITY   1
#define ADC_READ_PRIORITY  -1
#define THREAD_START_DELAY 100

#endif // REEFER_INCLUDE_CONFIG_H