name: FSW Setup
description: |
  This workflow sets up the dependencies for supporting FSW testing.
runs:
  using: "composite"
  steps:
    - name: Add 32bit
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo dpkg --add-architecture i386 
        sudo apt update
    - name: Compute Cache Hashes
      id: compute_hashes
      shell: bash
      run: |
        echo "ZEPHYR_HASH=${{ hashFiles('FSW/west.yml', 'FSW/zephyr/module.yml') }}" >> $GITHUB_ENV

    - uses: awalsh128/cache-apt-pkgs-action@latest
      if: runner.os == 'Linux'
      with:
        packages: pkg-config libfuse-dev:i386 gcc-multilib g++-multilib
        version: 1.0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip

    - name: Cache Zephyr dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/west
          ~/.cache/zephyr
          ~/.west
          modules
        key: zephyr-samples-${{ runner.os }}-${{ env.ZEPHYR_HASH }}
        restore-keys: |
          zephyr-samples-${{ runner.os }}-

    - name: Setup Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1.0.6
      with:
        app-path: FSW
        toolchains: arm-zephyr-eabi
        manifest-file-name: west.yml
