name: FSW Setup
description: |
  This workflow sets up the dependencies for supporting FSW testing.
runs:
  using: "composite"
  steps:
    - name: Compute Cache Hashes
      id: compute_hashes
      shell: bash
      run: |
        echo "ZEPHYR_HASH=${{ hashFiles('FSW/west.yml', 'FSW/zephyr/module.yml') }}" >> $GITHUB_ENV

    - name: Install Native Sim Dependencies (Linux)
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Linux" ]; then 
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y pkg-config libfuse-dev:i386 gcc-multilib g++-multilib;
        fi

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip

    - name: Cache Zephyr dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/west
          ~/.cache/zephyr
          ~/.west
          modules
        key: zephyr-samples-${{ runner.os }}-${{ env.ZEPHYR_HASH }}
        restore-keys: |
          zephyr-samples-${{ runner.os }}-

    - name: Setup Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1.0.6
      with:
        app-path: FSW
        toolchains: arm-zephyr-eabi
