radio:
	west build -b radio_module app/backplane/radio_module -p auto -DDEBUG=y

radio-flight:
	west build -b radio_module app/backplane/radio_module -p auto

radio-rcv:
	west build -b radio_module app/backplane/radio_module -p auto -DCONFIG_RADIO_MODULE_RECEIVER=y
