/// THIS CODE IS GENERATED BY AN AUTOCODER (DO NOT EDIT)
// Reference Files:
{% for file in files %}
// - {{ file }}
{% endfor %}

#ifndef _AUTOCODED_TYPES_H_
#define _AUTOCODED_TYPES_H_

#include <stdint.h>

namespace NTypes {

{% for type in types %}
    typedef struct __attribute__((packed))
    {
        {% for field in common_fields %}
        {{ field.type }} {{ field.name }};
        {% endfor %}
    } {{ type.name }};

{% endfor %}
}

#endif // _AUTOCODED_TYPES_H_