/// THIS CODE IS GENERATED BY AN AUTOCODER (DO NOT EDIT)
// Reference Files: {% for file in files %}
// - {{ file }}
{% endfor %}
#ifndef _AUTOCODED_TYPES_H_
#define _AUTOCODED_TYPES_H_

#include <stdint.h>

namespace NTypes { {% for t in types %}
    // {{ t[1].description }}
    typedef struct __attribute__((packed)) {
        {%- for field in t[1].fields %}
        {{ field.type }} {{ field.name }}; {% endfor %}
    } {{ t[0] }};
{% endfor -%}
}

#endif // _AUTOCODED_TYPES_H_
